version: 0.0
os: linux

files:
    - source: /
      destination: /home/ec2-user/leafy-front
      overwrite: yes

permissions:
    - object: /
      pattern: '**'
      owner: ec2-user
      group: ec2-user

hooks:
    AfterInstall:
        - location: shell/deploy.sh
          timeout: 60
          runas: ec2-user
