version: 0.0
os: linux

files:
    - source: /
      destination: /home/ec2-user/leafy-front
      overwrite: yes

permissions:
    - object: /
      pattern: '**'
      owner: ec2-user
      group: ec2-user

environment:
    variables:
        REACT_APP_MODE: ${{ secrets.REACT_APP_MODE }}

hooks:
    ApplicationStart:
        - location: shell/deploy.sh
          timeout: 100
          runas: ec2-user
