import { colors } from "./style.config";

const uiConfigs = {
  light: {
    green: {
      borderColor: colors.transparent,
      background: colors.transparent,
      color: colors.lgreen,
      focusBorder: colors.vert,
      foucsBackground: colors.vert,
      focusColor: colors.white,
      hoverBorder: colors.bgreen,
      hoverBackground: colors.bgreen,
      hoverColor: colors.white,
      activeBorder: colors.green,
      activeBackground: colors.green,
      activeColor: colors.white,
    },
    greenBorder: {
      borderColor: colors.lgreen,
      background: colors.transparent,
      color: colors.lgreen,
      focusBorder: colors.vert,
      foucsBackground: colors.vert,
      focusColor: colors.white,
      hoverBorder: colors.bgreen,
      hoverBackground: colors.white,
      hoverColor: colors.bgreen,
      activeBorder: colors.green,
      activeBackground: colors.green,
      activeColor: colors.white,
    },
    red: {
      borderColor: colors.red,
      background: colors.red,
      color: colors.white,
      focusBorder: colors.red,
      foucsBackground: colors.red,
      focusColor: colors.white,
      hoverBorder: colors.tdred_600,
      hoverBackground: colors.tdred_600,
      hoverColor: colors.white,
      activeBorder: colors.tdred_900,
      activeBackground: colors.tdred_900,
      activeColor: colors.white,
    },
    backgroundColor: colors.white,
  },
  dark: {
    green: {
      borderColor: colors.transparent,
      background: colors.transparent,
      color: colors.white,
      hoverBackground: colors.bgreen,
      hoverColor: colors.bgreen,
    },
    greenBorder: {
      borderColor: colors.white,
      background: colors.transparent,
      color: colors.white,
      focusBorder: colors.vert,
      foucsBackground: colors.vert,
      focusColor: colors.white,
      hoverBorder: colors.bgreen,
      hoverBackground: colors.white,
      hoverColor: colors.bgreen,
      activeBorder: colors.green,
      activeBackground: colors.green,
      activeColor: colors.white,
    },
    red: {
      borderColor: colors.lgreen,
      background: colors.transparent,
      color: colors.lgreen,
      focusBorder: colors.vert,
      foucsBackground: colors.vert,
      focusColor: colors.white,
      hoverBorder: colors.bgreen,
      hoverBackground: colors.white,
      hoverColor: colors.bgreen,
      activeBorder: colors.green,
      activeBackground: colors.green,
      activeColor: colors.white,
    },
    backgroundColor: colors.dark,
  },
};

export default uiConfigs;
