import { colors } from './style.config';

const uiConfigs = {
    light: {
        default: {
            borderColor: colors.gray,
            background: colors.transparent,
            color: colors.black,
            hoverBorder: colors.gray_300,
            hoverBackground: colors.gray_300,
            hoverColor: colors.white,
        },
        gray: {
            borderColor: colors.gray_200,
            background: colors.gray_100,
            color: colors.black,
            hoverBorder: colors.gray_300,
            hoverBackground: colors.gray_300,
            hoverColor: colors.white,
        },
        green: {
            borderColor: colors.lgreen,
            background: colors.transparent,
            color: colors.lgreen,
            focusBorder: colors.vert,
            foucsBackground: colors.vert,
            focusColor: colors.white,
            hoverBorder: colors.bgreen,
            hoverBackground: colors.bgreen,
            hoverColor: colors.white,
            activeBorder: colors.green,
            activeBackground: colors.green,
            activeColor: colors.white,
        },
        greenFill: {
            borderColor: colors.vigreen_800,
            background: colors.green,
            color: colors.white,
            focusBorder: colors.vert,
            foucsBackground: colors.vert,
            focusColor: colors.white,
            hoverBorder: colors.bgreen,
            hoverBackground: colors.bgreen,
            hoverColor: colors.white,
            activeBorder: colors.green,
            activeBackground: colors.green,
            activeColor: colors.white,
        },
        greenBorder: {
            borderColor: colors.lgreen,
            background: colors.transparent,
            color: colors.lgreen,
            focusBorder: colors.vert,
            foucsBackground: colors.vert,
            focusColor: colors.white,
            hoverBorder: colors.bgreen,
            hoverBackground: colors.white,
            hoverColor: colors.bgreen,
            activeBorder: colors.green,
            activeBackground: colors.green,
            activeColor: colors.white,
        },
        red: {
            borderColor: colors.red,
            background: colors.red,
            color: colors.white,
            focusBorder: colors.red,
            foucsBackground: colors.red,
            focusColor: colors.white,
            hoverBorder: colors.tdred_600,
            hoverBackground: colors.tdred_600,
            hoverColor: colors.white,
            activeBorder: colors.tdred_900,
            activeBackground: colors.tdred_900,
            activeColor: colors.white,
        },
        normal: {
            color: colors.black,
            backgroundColor: colors.white,
        },
    },
    dark: {
        default: {
            borderColor: colors.gray,
            background: colors.transparent,
            color: colors.white,
            hoverBorder: colors.gray_300,
            hoverBackground: colors.gray_300,
            hoverColor: colors.white,
        },
        gray: {
            borderColor: colors.gray,
            background: colors.white,
            color: colors.black,
            hoverBorder: colors.green,
            hoverBackground: colors.bgreen,
            hoverColor: colors.white,
        },
        green: {
            borderColor: colors.vigreen_100,
            background: colors.vigreen_900,
            color: colors.white,
            focusBorder: colors.vert,
            foucsBackground: colors.vert,
            focusColor: colors.white,
            hoverBorder: colors.bgreen,
            hoverBackground: colors.bgreen,
            hoverColor: colors.white,
            activeBorder: colors.green,
            activeBackground: colors.green,
            activeColor: colors.white,
        },
        greenFill: {
            borderColor: colors.vigreen_700,
            background: colors.vigreen_900,
            color: colors.white,
            focusBorder: colors.vert,
            foucsBackground: colors.vert,
            focusColor: colors.white,
            hoverBorder: colors.bgreen,
            hoverBackground: colors.bgreen,
            hoverColor: colors.white,
            activeBorder: colors.green,
            activeBackground: colors.green,
            activeColor: colors.white,
        },
        greenBorder: {
            borderColor: colors.white,
            background: colors.transparent,
            color: colors.white,
            focusBorder: colors.vert,
            foucsBackground: colors.vert,
            focusColor: colors.white,
            hoverBorder: colors.bgreen,
            hoverBackground: colors.white,
            hoverColor: colors.bgreen,
            activeBorder: colors.green,
            activeBackground: colors.green,
            activeColor: colors.white,
        },
        red: {
            borderColor: colors.lgreen,
            background: colors.transparent,
            color: colors.lgreen,
            focusBorder: colors.vert,
            foucsBackground: colors.vert,
            focusColor: colors.white,
            hoverBorder: colors.bgreen,
            hoverBackground: colors.white,
            hoverColor: colors.bgreen,
            activeBorder: colors.green,
            activeBackground: colors.green,
            activeColor: colors.white,
        },
        normal: {
            color: colors.white,
            backgroundColor: colors.black,
        },
    },
};

export default uiConfigs;
